# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
height: 400
plugins:
  - table
  - fullscreen
  - safari 
  - spellchecker 
  - pagebreak   
  - insertdatetime 
  - media 
  - searchreplace 
  - paste 
  - directionality
  - noneditable 
  - visualchars 
  - nonbreaking 
  - xhtmlxtras
theme_advanced_buttons1:
  - save 
  - newdocument 
  - | 
  - cut 
  - copy 
  - paste 
  - pastetext 
  - pasteword 
  - | 
  - undo 
  - redo 
  - | 
  - search 
  - replace 
  - | 
  - bold 
  - italic 
  - underline 
  - strikethrough 
  - | 
  - sub 
  - sup 
  - | 
  - forecolor 
  - backcolor 
  - | 
  - justifyleft 
  - justifycenter 
  - justifyright 
  - justifyfull 
  - | 
  - bullist 
  - numlist 
  - | 
  - outdent 
  - indent 
  - | 
  - formatselect 
  - fontselect 
  - fontsizeselect
theme_advanced_buttons2:
  - blockquote  
  - | 
  - link 
  - unlink 
  - cleanup 
  - | 
  - insertdate 
  - inserttime 
  - preview 
  - | 
  - tablecontrols 
  - | 
  - hr 
  - removeformat 
  - visualaid 
  - | 
  - charmap 
  - iespell 
  - advhr 
  - | 
  - print 
  - | 
  - fullscreen 
  - | 
  - insertlayer 
  - moveforward 
  - movebackward 
  - absolute 
  - | 
  - spellchecker 
  - | 
  - cite 
  - abbr 
  - acronym 
  - del 
  - ins 
  - | 
  - visualchars 
  - nonbreaking 
  - template 
  - blockquote 
  - pagebreak
theme_advanced_buttons3: -
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_resizing: true
entities: 
  - 160 
  - nbsp
  - 38
  - amp
  - 34 
  - quot 
  - 162 
  - cent 
  - 8364
  - euro 
  - 163 
  - pound 
  - 165 
  - yen 
  - 169 
  - copy 
  - 174 
  - reg 
  - 8482 
  - trade 
  - 8240 
  - permil
  - 60
  - lt 
  - 62
  - gt
  - 8804
  - le
  - 8805
  - ge
  - 176
  - deg
  - 8722
  - minus
entity_encoding: named
